# kubernetes/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cv-example-app-service
spec:
  selector:
    app: cv-example-app
  ports:
    - protocol: TCP
      port: 80 # The port clients will access the service on (e.g., http://localhost:30080:80)
      targetPort: 8080 # The port your application inside the container listens on
      nodePort: 30080 # A high port (30000-32767) exposed on your Rancher Desktop node
  type: NodePort # Exposes the service on a port on your host machine (Rancher Desktop VM)
